### PR TITLE
Fix use of 'send' where 'sent' is correct

### PR DESCRIPTION
**Pull request by reos-rcrozier**
This pull requests corrects the use of 'send' where 'sent' should be used, specifically in the metrics messages_send.

I'm going to admit I just edited the files online and haven't tested it, I don't even know rust, but I'm pretty sure my corrections are valid.

### CODE REVIEW

**Comment by reos-rcrozier** [comment]
I missed one messages_send occurrence, now replaced

**Comment by reos-rcrozier** [comment]
I don't know how to easily fix the DCO issue in my fork? Instructions seem to asumme you are working on the original repository.

**Comment by reos-rcrozier** [comment]
I modified the commits to ensure they are signed off by myself, but Github doesn't seem to like it.

**Comment by reos-rcrozier** [comment]
DCO issue has been resolved

**Comment by icewind1991** [comment]
Thanks!

**Pull request merged**
